bilayer_eq: false
box:
- 15
- 15
- 15
box_eq: false
boxscaling_xyz:
- true
- true
- true
cutoff_lj: 2.0
cutoff_yu: 4.0
eps_lj: 0.2
fixed_lambda: 0
frestart: restart.chk
friction_coeff: 0.001
gpu_id: 0
ionic: 0.1
k_eq: 0.02
logfreq: 1000000
pH: 7.5
platform: CUDA
pressure:
- 0
- 0
- 0
pressure_coupling: false
random_number_seed: null
report_potential_energy: false
restart: checkpoint
runtime: 0
slab_eq: false
slab_outer: 40
slab_width: 100
steps: 50000000
steps_eq: 1000
sysname: TDP43_0
temp: 300.0
threads: 1
topol: grid
verbose: true
wfreq: 100000
