bilayer_eq: false
box:
- 10.0
- 10.0
- 40.0
box_eq: false
boxscaling_xyz:
- true
- true
- true
custom_restraint_type: harmonic
custom_restraints: false
cutoff_lj: 2.0
cutoff_yu: 4.0
eps_lj: 0.2
ext_force: false
ext_force_expr: step(d2-18)*d2; d2=periodicdistance(x, y, z, 0, 0, z)^2
fcustom_restraints: custom_restraints.txt
fixed_lambda: 0
frestart: restart.chk
friction_coeff: 0.01
gpu_id: 0
ionic: 0.15
k_eq: 0.02
logfreq: 1000000
pH: 7.5
platform: CUDA
pressure:
- 0
- 0
- 0
pressure_coupling: false
random_number_seed: null
report_potential_energy: false
restart: checkpoint
runtime: 0
slab_eq: false
slab_outer: 40
slab_width: 40
steps: 5000000
steps_eq: 1000
sysname: TDP43_1
temp: 310.0
threads: 1
topol: slab
verbose: true
wfreq: 50000
